name: djEdilHernandez
favicon: null
layout_spectrum: 0.12778591038659215
typography_spectrum: 0.08148500905372202
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.955010243691504
  lightness: 0.7711678070481867
  saturation: 0.7449547697324306
  rhythmicContrast: 0.6743211869616061
purpose: []
